# .github/workflows/update-menu.yml
name: Update Weekly Menu

on:
  schedule:
    - cron: '0 0 * * 0'  # Every Sunday at 00:00 UTC
  workflow_dispatch:    # Allow manual trigger

jobs:
  update-menu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pdfplumber

      - name: Run script
        run: python pdf_menu_parser.py

      - name: Archive Café Bona menus
        uses: actions/upload-artifact@v4
        with:
          name: Café_Bona
          path: ./Café_Bona.json

      - name: Archive BuonPranzo menus
        uses: actions/upload-artifact@v4
        with:
          name: Buon_Pranzo
          path: Buon_Pranzo.json
